@HostAddress = http://localhost:5117/api
@Token = 

# Marca

### Criar
POST {{HostAddress}}/marca   HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "nome": "Marca Teste"
}

### Obter por Id
GET {{HostAddress}}/marca/1   HTTP/1.1
Accept: application/json

### Listar
GET {{HostAddress}}/marca   HTTP/1.1
Accept: application/json